### ISSUE TITLE
Non-static method cannot be referenced from a static context

### ISSUE THREAD

**Issue by sebastienvermeille** [raner/loginject#16]
Hi,
I wanted to use your guice extension it seems really good but sadly I can't instanciate it.

`Module module = loginject(Logger.class, LogManager::getLogger, currentClass()).as(Module.class);`

I have a compilation error : 

> Non-static method cannot be referenced from a static context

any idea ?

Thank you for your answer

**Comment by octaviospain** [comment]
Hello @sebastienvermeille,
I think that what you want to do is:
```
Module module = loginject(clazz -> LogManager.getLogManager(), currentClass()).as(Module.class);
```

**Comment by raner** [comment]
Looks like you guys got it all sorted out. Thanks, @octaviospain
